### ISSUE TITLE
Bug About Unknown Object Detection

### ISSUE THREAD

**Issue by Zengyf-CVer** [zldrobit/tfjs-yolov5-example#2]
@zldrobit 

Hello, I have done a lot of experiments on the application of the custom yolov5s model in the tfjs project and found a bug.
When you enter an image of a known category, the detection is normal:
![image](https://user-images.githubusercontent.com/41098760/124915247-e7101480-e023-11eb-9c47-d3dec81f8c51.png)
When you enter an image of an unknown category, an error like this will be reported on the chrome console:
![image](https://user-images.githubusercontent.com/41098760/124915381-0b6bf100-e024-11eb-9c09-4f1eccf2affc.png)
My initial analysis is the issue of the `executeAsync` function in `tf.loadGraphModel(weights).executeAsync(input)`.
I hope you can test it and look forward to your reply.

**Comment by zldrobit** [comment]
I can reproduce this problem and confirm the issue resides in the `executeAsync()` model execution.
The error still exists if I comment the function body after inference https://github.com/zldrobit/tfjs-yolov5-example/blob/12267bfddd67940ec8b4e8e8e4c0439ffb20820f/src/index.js#L75-L116 but not after I comment the whole promise block https://github.com/zldrobit/tfjs-yolov5-example/blob/12267bfddd67940ec8b4e8e8e4c0439ffb20820f/src/index.js#L74-L117

There are related issues in TensorFlow's repo: https://github.com/tensorflow/tfjs/issues/2375, https://github.com/tensorflow/tfjs/issues/2737. Neither of them is resolved. It seems the problem is in TensorFlow.js.

**Comment by Zengyf-CVer** [comment]
I think it is also a problem with tfjs, thank you very much.

**Comment by Zengyf-CVer** [comment]
The problem of abnormal null values has been solved, please download the latest version of TFJS (3.9.0).

**Comment by zldrobit** [comment]
Thanks for letting me know :D
